"""This template outlines a provider for the server-to-sitekick code. Copy this file to a new file in the providers
directory, and change the functions to suit your needs. The functions are:
is_server_type()    Returns True-ish if the server on which the server is running, is of the appropriate type.
                    Returns False-ish or raise an error if not the specified type, so you can just call any function
                    to determine whether the server is of the appropriate type.
get_domains()       Get all domains from the local hosting server. Return a complete list of domain names.
get_domain_info()   Get detailed information about the specified domain from the local hosting server.
                    Return a dictionary with the domain info. The domain name is added to the dictionary under the
                    key 'domain'. When additional or different info is needed, change this function.

It can also contain a number of optional constants, which can be used to change the behaviour of the server-to-sitekick
code. The constants are:
EXECUTE_PARALLEL        Whether to execute the get_domains_info() and push_domains_info() calls in parallel. True when
                        not specified.
DOMAIN_COUNT_PER_POST   Number of detailed domain info packages to send per post. Defaults to
                        sitekick.send.DOMAIN_COUNT_PER_POST
DOMAIN_POST_INTERVAL    Seconds, interval between posts. Defaults to sitekick.send.DOMAIN_POST_INTERVAL
"""
from sitekick.utils import now, hostname, ip_address, mac_address

EXECUTE_PARALLEL = False
DOMAIN_COUNT_PER_POST = 20  # Count and interval are optionally specified per module
DOMAIN_POST_INTERVAL = 1

def is_server_type():
    """Returns True-ish if the server on which the server is running, is of the specified type.
    Any non-False suffices, but extra information (like the server type and version) can be returned.
    E.g. when on a plesk-server the code `providers.plesk.is_server_type() is called, it returns a string with
    the version info."""
    return hostname == 'zh-dev-omni-001'


def get_domains():
    """Get all domains from the local hosting server."""
    return [f"domain-{i:03}.com" for i in range(1, 10001)]


def get_domain_info(domain):
    """Get detailed information about the specified domain from the local hosting server.
    When additional or different info is needed, change this function."""
    data = {
     'domain': domain,
     'info': '\n'
             'General\n'
             '=============================\n'
             'Domain ID:                              1\n'
             'Domain name:                            sitekick.eu\n'
             "Owner's contact name:                   Administrator (admin)\n"
             'Domain status:                          OK\n'
             'Creation date:                          Oct 20, 2023\n'
             'Expiration date:                        Unlimited\n'
             'Disk space limit:                       Unlimited\n'
             'Size:                                   121 MB\n'
             'Total size of backup files in local storage:0 B\n'
             'Traffic limit:                          Unlimited\n'
             'Traffic:                                5.13 KB/Month\n'
             'Description:                            \n'
             'Description for the administrator:      \n'
             'External ID:                            \n'
             '\n'
             'Hosting\n'
             '=============================\n'
             'Hosting type:                           Physical hosting\n'
             'IP Address:                             145.131.8.226\n'
             'FTP Login:                              sitekick.eu_34gqrbu1k9m\n'
             'FTP Password:                           ************\n'
             "SSH access to the server shell under the subscription's system "
             'user:/bin/false\n'
             'Hard disk quota:                        Unlimited (not '
             'supported)\n'
             'Disk space used by httpdocs:            119 MB\n'
             'Disk space used by Log files and statistical reports:196 KB\n'
             'Certificate:                            \n'
             'SSL/TLS support:                        On\n'
             'Permanent SEO-safe 301 redirect from HTTP to HTTPS:On\n'
             'SSI support:                            No\n'
             'PHP support:                            Yes\n'
             'CGI support:                            No\n'
             'Perl support:                           No\n'
             'Python support:                         No\n'
             'FastCGI support:                        Yes\n'
             'Custom error documents:                 Yes\n'
             'Web statistics:                         AWStats\n'
             'Anonymous FTP:                          No\n'
             'Disk space used by Anonymous FTP:       0 B\n'
             '\n'
             'Web Users\n'
             '=============================\n'
             'Total :                                 0\n'
             'SSI support:                            0\n'
             'PHP support:                            0\n'
             'CGI support:                            0\n'
             'Perl support:                           0\n'
             'Python support:                         0\n'
             'FastCGI support:                        0\n'
             'Total size:                             0 B\n'
             '\n'
             'Mail Accounts\n'
             '=============================\n'
             'Mail service:                           On\n'
             'Total :                                 3\n'
             'Access to Plesk:                        0\n'
             'Mailboxes:                              3\n'
             'Mail forwardings:                       0\n'
             'Auto-replies:                           0\n'
             'Total size:                             96.0 KB\n'
             'Mail autodiscover:                      On\n'
             '\n'
             'Mailing Lists\n'
             '=============================\n'
             'Mailing list service:                   Off\n'
             'Total :                                 0\n'
             'Total size:                             0 B\n'
             '\n'
             'Databases\n'
             '=============================\n'
             'Total :                                 1\n'
             'Total size:                             1.24 MB\n'
             '\n'
             'Web Applications\n'
             '=============================\n'
             'Total :                                 0\n'
             '\n'
             '\n'
             'Logrotation info\n'
             '==============================\n'
             'Log rotation status:                    On\n'
             'Log rotation condition:                 10240KB (by size)\n'
             'Maximum number of log files:            10\n'
             'Compress log files:                     true\n'
             'Send processed log files to email:      \n'
             '\n'
             '\n'
             '--WWW-Root--: /var/www/vhosts/sitekick.eu/httpdocs\n'
             '\n'
             '\n'
             'Subscription Information\n'
             '==============================\n'
             'The domain is subscribed to the service plan "Unlimited" of '
             'Administrator.\n'
             'The subscription is not locked for syncing.\n'
             '\n'
             '\n'
             "SUCCESS: Gathering information for 'sitekick.eu' completed.\n",
     'wp_plugins': 'ID                                 2\n'
                   'Main Domain ID                     1\n'
                   'Installation Path                  /httpdocs\n'
                   'Owner ID                           1\n'
                   'GUID                               '
                   '1f47ea4c-8a10-4355-ad82-bd847ab6b2ba\n'
                   'State                              Outdated PHP\n'
                   'Website URL                        https://sitekick.eu\n'
                   'Login URL                          '
                   'https://sitekick.eu/wp-login.php\n'
                   'Name                               Sitekick\n'
                   'Version                            6.8.2\n'
                   "Administrator's email              "
                   'root@beautiful-greider.145-131-8-226.plesk.page\n'
                   'Automatic updates                  Major and Minor\n'
                   'Search Engine Indexing             true\n'
                   'Security Status                    '
                   '[[controllers.index.detail.securityStatusSecureRecommended]]\n'
                   'SSL/TLS                            No certificate\n'
                   'Full Path                          '
                   '/var/www/vhosts/sitekick.eu/httpdocs\n'
                   '\n'
                   'Plugins\n'
                   '***********************************\n'
                   'Name                               akismet\n'
                   'Status                             inactive\n'
                   'Version                            5.4\n'
                   'Title                              Akismet Anti-spam: Spam '
                   'Protection\n'
                   'Description                        Used by millions, '
                   'Akismet is quite possibly the best way in the world to\n'
                   '<strong>protect your blog from spam</strong>. Akismet '
                   'Anti-spam keeps your\n'
                   'site protected even while you sleep. To get started: '
                   'activate the Akismet\n'
                   'plugin and then go to your Akismet Settings page to set up '
                   'your API key.\n'
                   'Latest Version                     5.5\n'
                   'Autoupdates                        false\n'
                   'Source identity                    1\n'
                   'Blocked                            false\n'
                   '\n'
                   'Name                               hello\n'
                   'Status                             active\n'
                   'Version                            1.7.2\n'
                   'Title                              Hello Dolly\n'
                   'Description                        This is not just a '
                   'plugin, it symbolizes the hope and enthusiasm of an\n'
                   'entire generation summed up in two words sung most famously '
                   'by Louis\n'
                   'Armstrong: Hello, Dolly. When activated you will randomly '
                   'see a lyric from\n'
                   '<cite>Hello, Dolly</cite> in the upper right of your admin '
                   'screen on every\n'
                   'page.\n'
                   'Autoupdates                        false\n'
                   'Source identity                    1\n'
                   'Blocked                            false\n'
                   '\n'
                   'Name                               google-site-kit\n'
                   'Status                             active\n'
                   'Version                            1.161.0\n'
                   'Title                              Site Kit by Google\n'
                   'Description                        Site Kit is a one-stop '
                   'solution for WordPress users to use everything\n'
                   'Google has to offer to make them successful on the web.\n'
                   'Autoupdates                        false\n'
                   'Source identity                    1\n'
                   'Blocked                            false\n'
                   '\n'
                   'Name                               wordpress-seo\n'
                   'Status                             active\n'
                   'Version                            25.9\n'
                   'Title                              Yoast SEO\n'
                   'Description                        The first true '
                   'all-in-one SEO solution for WordPress, including on-page\n'
                   'content analysis, XML sitemaps and much more.\n'
                   'Autoupdates                        true\n'
                   'Source identity                    1\n'
                   'Blocked                            false\n'
                   '\n'
                   '\n'
                   'Themes\n'
                   '***********************************\n'
                   'Name                               twentytwentyfive\n'
                   'Status                             active\n'
                   'Version                            1.3\n'
                   'Title                              Twenty Twenty-Five\n'
                   'Description                        Twenty Twenty-Five '
                   'emphasizes simplicity and adaptability. It offers\n'
                   'flexible design options, supported by a variety of patterns '
                   'for different\n'
                   'page types, such as services and landing pages, making it '
                   'ideal for\n'
                   'building personal blogs, professional portfolios, online '
                   'magazines, or\n'
                   'business websites. Its templates cater to various blog '
                   'styles, from\n'
                   'text-focused to image-heavy layouts. Additionally, it '
                   'supports\n'
                   'international typography and diverse color palettes, '
                   'ensuring accessibility\n'
                   'and customization for users worldwide.\n'
                   'Autoupdates                        false\n'
                   'Source identity                    1\n'
                   '\n'
                   'Name                               twentytwentyfour\n'
                   'Status                             inactive\n'
                   'Version                            1.3\n'
                   'Title                              Twenty Twenty-Four\n'
                   'Description                        Twenty Twenty-Four is '
                   'designed to be flexible, versatile and applicable to\n'
                   'any website. Its collection of templates and patterns '
                   'tailor to different\n'
                   'needs, such as presenting a business, blogging and writing '
                   'or showcasing\n'
                   'work. A multitude of possibilities open up with just a few '
                   'adjustments to\n'
                   'color and typography. Twenty Twenty-Four comes with style '
                   'variations and\n'
                   'full page designs to help speed up the site building '
                   'process, is fully\n'
                   'compatible with the site editor, and takes advantage of new '
                   'design tools\n'
                   'introduced in WordPress 6.4.\n'
                   'Autoupdates                        false\n'
                   'Source identity                    1\n'
                   '\n'
                   'Name                               twentytwentythree\n'
                   'Status                             inactive\n'
                   'Version                            1.6\n'
                   'Title                              Twenty Twenty-Three\n'
                   'Description                        Twenty Twenty-Three is '
                   'designed to take advantage of the new design tools\n'
                   'introduced in WordPress 6.1. With a clean, blank base as a '
                   'starting point,\n'
                   'this default theme includes ten diverse style variations '
                   'created by members\n'
                   'of the WordPress community. Whether you want to build a '
                   'complex or\n'
                   'incredibly simple website, you can do it quickly and '
                   'intuitively through\n'
                   'the bundled styles or dive into creation and full '
                   'customization yourself.\n'
                   'Autoupdates                        false\n'
                   'Source identity                    1\n'
                   '\n'
                   '\n'}
    return data
    import time
    # time.sleep(0.01)
    return {'domain': domain, 'ip': ip_address, 'mac': mac_address, 'hostname': hostname, 'now': now()}
